### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SilversApprentice**
just fixed a minor typ

### CODE REVIEW

**Comment by card100** [comment]
Whatever OS?  Finally, a good OS!

**Comment by SpooikypokDev** [comment]
This PR was strangely hard to make, because I wasn't familiar with GitHub. I tried to make a PR about five times. The first times, my PR was welcomed with a kind access denied message, and then I succeeded to clone the repository, but the mac suddenly powered itself off, but I finally

**Comment by SpooikypokDev** [comment]
We should close this, shouldn't we? It was superseded by #2.

**Comment by SilversApprentice** [comment]
@algorev yeah

**Pull request closed without merging**
